### ISSUE TITLE
@global is broken

### ISSUE THREAD

**Issue by alekangelov** [LXSMNSYC/solid-styled#18]
Hello,

the @global rule seems to be broken

it's wrapping the styles in an "@global {...}"

```tsx
function App() {
    css`
        @global { body { background: white } }
    `
    return <main />
}
```

should compile to

```css
body { background: white }
```

but instead it compiles to

```css
@global { body { background: white } }
```

downgrading to 0.8.2 fixed the issue. maybe due to moving away from postcss?
