### ISSUE TITLE
Animation css in wrong order

### ISSUE THREAD

**Issue by AverTry** [LXSMNSYC/solid-styled#31]
Hi, both scoped and global, reorder css and prevents proper animation.

Working fine in normally imported CSS and Module imported CSS

Error only occurs with solid-styled v0.10.0

Correct Order:
```css
      .revealingImage {
        view-timeline-name: --revealing-image;
        view-timeline-axis: block;

        animation: linear reveal both;
        animation-timeline: --revealing-image;
        animation-range: cover 10% contain 40%;
      }
```
Error using \<styles jsx\>, css\`\` 

![image](https://github.com/lxsmnsyc/solid-styled/assets/72357571/58682134-ac8d-428a-8e4b-a05b7199ec0f)

Error using \<styles jsx global\>

![image](https://github.com/lxsmnsyc/solid-styled/assets/72357571/cd306257-29d1-410e-a3cd-db975738808a)

After manually changing in browser dev tools to get it working 

![image](https://github.com/lxsmnsyc/solid-styled/assets/72357571/35519d89-fa51-44a4-b691-5c3d63ce1f34)

Source Code and Polyfill js taken from [https://developer.chrome.com/docs/css-ui/scroll-driven-animations](https://developer.chrome.com/docs/css-ui/scroll-driven-animations)

New CSS properties for 2024
